run_dirs:
  - flexible_self_docking # this specifies which equibind model to use. can try train on both?

inference_path: 'data/train' # this should be your input file path as described in the main readme

output_directory: 'hidden_layers' # the hidden layers will be saved here

layer: 'both' # which layer do you want (ligand or receptor or both)